@echo off
echo Starting GST Fraud Detection System...

echo Launching Backend (FastAPI)...
start "GST Backend" cmd /k "cd backend && python -m uvicorn app:app --reload --port 8000"

echo Launching Frontend (Vite)...
cd frontend && npm run dev
